inherit_from: .rubocop_todo.yml
require: rubocop-rspec

RegexpLiteral:
  Exclude:
    - '**/Guardfile'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/Documentation:
  Exclude:
    - '**/*.rb'
